### ISSUE TITLE
Reading PEM key for the purpose of finding a matching certificate

### ISSUE THREAD

**Issue by Rush** [Southern/node-x509#10]
I would like to ask here for RFC.
https://github.com/CodeCharmLtd/node-x509/tree/parse-pem
I have added a method: `persePem` which would return an object with fields `publicModulus` and `publicExponent`. Same fields have been added to `parseCert`. 
If both cert and pem have the same values - they are a matching pair. I think this belong to `node-x509` quite well but I would like to get a second opinion and before I do a second pull request the first one needs to get finished.

**Comment by Southern** [comment]
@Rush Sorry that I haven't been around in a while. Looks like we're exposing the modulus and exponent as `publicKey.n` and `publicKey.e` now. Is there any other problem related to this issue?

**Comment by Southern** [comment]
Closing this for now. Let me know if this is still an issue at any point.

**Comment by yorkie** [comment]
Wow @Southern You are so activity recently :+1:

**Comment by Southern** [comment]
@yorkie Yeah. I found a little time to go through and clean up some of the issues that we had in here. Everything should be good for now. :)
