### ISSUE TITLE
virtkick-proxy not available

### ISSUE THREAD

**Issue by dalareo** [Southern/node-x509#20]
I get git fetch -a origin (git://github.com/virtkick/virtkick-proxy.git) fatal: remote error: when installing virtkick-starter

**Comment by yorkie** [comment]
i guess you should use git+https://git@github.com/virtkick/virtkick-proxy.git

**Comment by dalareo** [comment]
The repository is no more available https://github.com/virtkick/virtkick-proxy gives 404 error

**Comment by yorkie** [comment]
Why do you care about this repo, it's not related to X509, sorry

**Comment by dalareo** [comment]
sorry, @yorkie I don't understand how or when, but my comment hit up a wrong thread. sorry...
