### ISSUE TITLE
Unhandled rejection error

### ISSUE THREAD

**Issue by heikoholland** [Southern/node-x509#25]
When I call parseCert with a wrong cert file like this parseCert('notreallyacrtfile.crt') I get

```
Unhandled rejection Error: Unable to parse certificate.
    at Error (native)
```

and I'm not able to catch that error.

**Comment by yorkie** [comment]
How do you try to catch the error, may I ask you to post more complete example? Thanks

**Comment by heikoholland** [comment]
I found the error in my code. Sorry for rushing in opening an issue.

**Comment by yorkie** [comment]
:-) You are welcome
