### ISSUE TITLE
Does not correctly release the file once read

### ISSUE THREAD

**Issue by weagle08** [Southern/node-x509#28]
the file does not seem to be getting closed correctly after reading. I can not delete the file after it is read without first stopping the node process.

**Comment by Southern** [comment]
@weagle08 can you check out the branch "issue-28", rebuild, and test with that? I think all it's lacking is the `BIO_free` that I added in on that branch.

**Comment by weagle08** [comment]
I'm not seeing that branch

**Comment by Southern** [comment]
@weagle08 I've already merged it into master and deleted that branch. Just pull the master branch and test it out if you don't mind.
