### ISSUE TITLE
NAN failing on Travis

### ISSUE THREAD

**Issue by Southern** [Southern/node-x509#31]
Related to #30; still failing to build NAN on Travis.

https://travis-ci.org/nickclaw/alexa-ability-express-handler/jobs/110630761

**Comment by Southern** [comment]
@nickclaw Can you try using `"x509": "git://github.com/Southern/node-x509.git#devel"` in a separate branch from your master? I want to see if it's as simple as updating the NAN dependency. It was behind a few versions.

**Comment by nickclaw** [comment]
I won't have access to that project until later tonight. It may be worth testing on the most recent versions of node, just in case that's what's going wrong. v4.3.1 and v5.6.0 are the current targets.

**Comment by Southern** [comment]
The current stable that was installed during the Travis tests is 5.6.0 and it passed before bumping to 0.2.4. That's strange. Try that branch when you can and let me know what the result is. I'm interested to know what's going on here.

**Comment by nickclaw** [comment]
https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements

I'm willing to bet this is it. But I'll try both tonight.

**Comment by nickclaw** [comment]
^ fixed it entirely. That's what I get for skimming through the logs.

**Comment by Southern** [comment]
Nice! I don't have to push another update! Going to close this since that worked.

Thanks again.
