### ISSUE TITLE
Does not compile with node 12.x

### ISSUE THREAD

**Issue by risacher** [Southern/node-x509#83]
does not compile against node 12.  Specifically tested on 12.10.0.  (On Ubuntu 18.04)

**Comment by codebling** [comment]
That's an issue with `nan`, but to be fair, even if it's fixed upstream, this package will still be broken because of the version spec. Right now it's locked at `"nan": "2.12.0"`, I think it makes more sense for it to be `^2.12.0`.

**Comment by matthew119427** [comment]
Any way to fix this? Having the same issue.

**Comment by tgabi333** [comment]
See: https://github.com/Southern/node-x509/pull/82

**Comment by risacher** [comment]
Dup #82

**Comment by codebling** [comment]
#82 has been superseded by #84 .

**Comment by codebling** [comment]
@ghaiklor published an NPM module with the fixes here -> https://www.npmjs.com/package/@ghaiklor/x509
